image: node:8.9.4

stages:
  - install
  - test
  - gatsby-build
  - deploy

install:
  stage: install
  script: npm install
  artifacts:
    paths:
    - node_modules/

lint:
  stage: test
  script: npm run lint

gatsby-build:
  stage: gatsby-build
  script: npm run build
  artifacts:
    paths:
    - public/

pages:
  stage: deploy
  script:
    - mkdir -p public/.well-known/acme-challenge/$CERT_FOLDER_ROOT
    - echo $CERT_CHALLENGE_ROOT > public/.well-known/acme-challenge/$CERT_FOLDER_ROOT/index.html
    - mkdir -p public/.well-known/acme-challenge/$CERT_FOLDER_WWW
    - echo $CERT_CHALLENGE_WWW > public/.well-known/acme-challenge/$CERT_FOLDER_WWW/index.html
  artifacts:
    paths:
      - public/
  only:
      - master
  dependencies:
  - gatsby-build
