image: node:8.9.4

stages:
  - install
  - test
  - gatsby-build
  - deploy

install:
  stage: install
  script: npm install
  artifacts:
    paths:
    - node_modules/

lint:
  stage: test
  script: npm run lint

gatsby-build:
  stage: gatsby-build
  script: npm run build
  artifacts:
    paths:
    - public/

pages:
  stage: deploy
  script:
    - ls -la public
    - mkdir -p public/.well-known/acme-challenge/Qiuj40XhtpEqiad6ZPFSJZmFPxwnZFaPwC0epeTxcYY
    - echo $CERT_CHALLENGE > public/.well-known/acme-challenge/Qiuj40XhtpEqiad6ZPFSJZmFPxwnZFaPwC0epeTxcYY/index.html
  artifacts:
    paths:
      - public/
  only:
      - master
  dependencies:
  - gatsby-build
