image: mhart/alpine-node:6.10.3

stages:
  - deploy

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - ls -la public
  artifacts:
    paths:
      - public/
  only:
      - master
