name: Adam James Clarkson
markdown: redcarpet
highlighter: pygments
destination: ./public
permalink: /:categories/:title/
tag_dir: tag
sass:
 style: compressed
exclude: ['scss','Gem','Guard','*.rb','.sass-cache','.git']